import { registerAllApplicationsComponent } from './allApplications/index.js'
import { registerCardCarouselSectionComponent } from './cardCarouselSection/index.js'
import { registerCaseSpotlightComponent } from './caseSpotlight/index.js'
import { registerCompanyScaleComponent } from './companyScale/index.js'
import { registerCustomizationGridComponent } from './customizationGrid/index.js'
import { registerFactoryMapComponent } from './factoryMap/index.js'
import { registerFocaHistoryTimelineComponent } from './focaHistoryTimeline/index.js'
import { registerHistoryTimelineComponent } from './historyTimeline/index.js'
import { registerHomeBannerCarouselComponent } from './homeBannerCarousel/index.js'
import { registerHotspotShowcaseComponent } from './hotspotShowcase/index.js'
import { registerMapComponent } from './map/index.js'
import { registerMilestoneCardStripComponent } from './milestoneCardStrip/index.js'
import { registerMoreCardCarouselComponent } from './moreCardCarousel/index.js'
import { registerOurAdvantagesComponent } from './ourAdvantages/index.js'
import { registerOverviewSplitComponent } from './overviewSplit/index.js'
import { registerProcessTimelineComponent } from './processTimeline/index.js'
import { registerProductCardStripComponent } from './productCardStrip/index.js'
import { registerResourceSectionComponent } from './resourceSection/index.js'
import { registerResponsiveHeroCarouselComponent } from './responsiveHeroCarousel/index.js'
import { registerServiceIconGridComponent } from './serviceIconGrid/index.js'
import { registerServicesCarouselComponent } from './servicesCarousel/index.js'
import { registerServicesShowcaseComponent } from './servicesShowcase/index.js'
import { registerServiceThbComponent } from './servicesThb/index.js'
import { registerSolutionListComponent } from './solutionList/index.js'
import { registerStaticPinMapComponent } from './staticPinMap/index.js'
import { registerStatsCardsComponent } from './statsCards/index.js'
import type { ComponentRegistryExecutor } from '../types.js'

export const BASIC_SECTION_REGISTRIES: ComponentRegistryExecutor[] = [
  { id: 'historyTimeline', register: registerHistoryTimelineComponent },
  { id: 'focaHistoryTimeline', register: registerFocaHistoryTimelineComponent },
  { id: 'productCardStrip', register: registerProductCardStripComponent },
  { id: 'caseSpotlight', register: registerCaseSpotlightComponent },
  { id: 'milestoneCardStrip', register: registerMilestoneCardStripComponent },
  { id: 'allApplications', register: registerAllApplicationsComponent },
  { id: 'moreCardCarousel', register: registerMoreCardCarouselComponent },
  { id: 'map', register: registerMapComponent },
  { id: 'staticPinMap', register: registerStaticPinMapComponent },
  { id: 'factoryMap', register: registerFactoryMapComponent },
  { id: 'statsCards', register: registerStatsCardsComponent },
  { id: 'customizationGrid', register: registerCustomizationGridComponent },
  { id: 'processTimeline', register: registerProcessTimelineComponent },
  { id: 'companyScale', register: registerCompanyScaleComponent },
  { id: 'solutionList', register: registerSolutionListComponent },
  { id: 'ourAdvantages', register: registerOurAdvantagesComponent },
  { id: 'serviceIconGrid', register: registerServiceIconGridComponent },
  { id: 'servicesCarousel', register: registerServicesCarouselComponent },
  { id: 'servicesShowcase', register: registerServicesShowcaseComponent },
  { id: 'serviceThb', register: registerServiceThbComponent },
  { id: 'responsiveHeroCarousel', register: registerResponsiveHeroCarouselComponent },
  { id: 'homeBannerCarousel', register: registerHomeBannerCarouselComponent },
  { id: 'overviewSplit', register: registerOverviewSplitComponent },
  { id: 'hotspotShowcase', register: registerHotspotShowcaseComponent },
  { id: 'resourceSection', register: registerResourceSectionComponent },
  { id: 'cardCarouselSection', register: registerCardCarouselSectionComponent },
]
